//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterTable
    {
        public int Id { get; set; }
        public string Ngay { get; set; }
        public string Gio { get; set; }
        public string Chinh { get; set; }
        public string Doi { get; set; }
        public string Noidung { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string Ghichu { get; set; }
        public string Nu { get; set; }
        public string Masokenh { get; set; }
    }
}
